---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/cv/svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: K. Bret Staudt Willet

jobtitle: "PhD Student, Michigan State University"
# address: ""
fontawesome: yes

email: bret@bretsw.com
linkedin: bretsw  # need to figure out how to link
github: bretsw
# phone: ""
web: bretsw.com
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue


# credit to Steven Miller
# http://svmiller.com/blog/2016/03/svm-r-markdown-cv/
# https://github.com/svmiller/svm-r-markdown-templates

# Rmarkdown guide: https://rmarkdown.rstudio.com/authoring_basics.html

---

# Education

*College of Education, Michigan State University*  
PhD Educational Psychology & Educational Technology \hfill 2016-present  
MA Educational Technology \hfill 2012-2015

*College of Arts & Sciences, Bucknell University*  
BA Mathematics & Sociology \hfill 1999-2003

# Publications

## Peer-Reviewed Journal Articles

Greenhalgh, S. P., Rosenberg, J. M., **Staudt Willet**, K. B., Koehler, M. J., & Akcaoglu, M. (under review). A time for all things: Comparing synchronous and asynchronous forms of participation in teacher-focused Twitter hashtags.

Greenhalgh, S. P., **Staudt Willet**, K. B., Rosenberg, J. M., & Koehler, M. J. (revise and resubmit). Tweet, and we shall find: Using digital methods to locate participants in educational hashtags.

Greenhow, C. M., Gleason, B., Marich, H., & **Staudt Willet**, K. B. (2017). Educating social scholars: Examining novice researchers’ practices with social media. *Qwerty – Open and Interdisciplinary Journal of Technology, Culture and Education, 12*(2), 30-45. Retrieved from http://www.ckbg.org/qwerty/index.php/qwerty/article/view/269

## Book Chapters

**Staudt Willet**, K. B., Koehler, M. J., & Greenhalgh, S. P. (2018). A tweet by any other frame: Three approaches to studying educator interactions on Twitter. In T. J. Bastiaens & G. Marks (Eds.), *Education and Information Technology Annual 2018: A Selection of AACE Award Papers* (pp. 67-74). Association for the Advancement of Computing in Education (AACE). Retrieved from http://learntechlib.org/p/182952/ [Invited reprint of conference presentation in edited book]

**Staudt Willet**, K. B., Koehler, M.J., & Greenhalgh, S.P. (2017). A tweet by any other frame: Comparing three theoretical frameworks for studying educator interactions on Twitter. In L. Liu & D. Gibson (Eds.), *Research highlights in technology and teacher education 2017* (pp. 63-70). Waynesville, NC: Association for the Advancement of Computing in Education (AACE). Retrieved from http://www.learntechlib.org/p/180960/ [Invited reprint of conference presentation in edited book]

## Peer-Reviewed Conference Proceedings

**Staudt Willet**, K. B., & Willet, B. D. (2018, October). *Look who’s talking: Using human coding to establish a machine learning approach to Twitter education chats.* Paper to be presented at the Association of Internet Researchers (AoIR) Annual Conference 2018, Montreal, Quebec, Canada.

**Staudt Willet**, K. B., & Reimer, P. N. (2018, March). The career you save may be your own: Exploring the mathtwitterblogosphere as a community of practice. In E. Langran & J. Borup (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2018* (pp. 2324-2329). Waynesville, NC: Association for the Advancement of Computing in Education (AACE).

**Staudt Willet**, K. B., Moudgalya, S., Boltz, L. O., Greenhalgh, S. P., & Koehler, M. J. (2018, March). Back to the gaming board: Understanding games and education through board game reviews. In E. Langran & J. Borup (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2018* (pp. 495-503). Waynesville, NC: Association for the Advancement of Computing in Education (AACE).

Greenhow, C., Marich, H., & **Staudt Willet**, K .B. (2017, March). Social scholars: Re-envisioning graduate education in the age of social media. In P. Resta & S. Smith (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2017* (pp. 856-861). Chesapeake, VA: Association for the Advancement of Computing in Education (AACE).

Rosenberg, J., Akcaoglu, M., **Staudt Willet**, K. B., Greenhalgh, S., & Koehler, M. (2017, March). A tale of two Twitters: Synchronous and asynchronous use of the same hashtag. In P. Resta & S. Smith (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2017* (pp. 283-286). Chesapeake, VA: Association for the Advancement of Computing in Education (AACE).

**Staudt Willet**, K. B., Koehler, M. J., & Greenhalgh, S. P. (2017, March). A tweet by any other frame: Three approaches to studying educator interactions on Twitter. In P. Resta & S. Smith (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2017* (pp. 1823-1830). Chesapeake, VA: Association for the Advancement of Computing in Education (AACE).

## Peer-Reviewed Conference Presentations

**Staudt Willet**, K. B. (2018, October). *Cyborg methods: The benefits of mixing human and machine coding.* Paper to be presented at the Association for Educational Communications and Technology (AECT) International Convention 2018. Kansas City, MO.

**Staudt Willet**, K. B. (2018, October). *Self-promoters, bots, and moderators: Exploring educators’ participatory actions, roles, and culture in Twitter #Edchat.* Paper to be presented at the Association for Educational Communications and Technology (AECT) International Convention 2018. Kansas City, MO.

**Staudt Willet**, K. B., Greenhalgh, S. P., Rosenberg, J. M., Koehler, M. J. (2018, October). *Won’t you be my neighbor? How education stakeholders use hyperlinks to build information neighborhoods on Twitter.* Paper to be presented at the Association for Educational Communications and Technology (AECT) International Convention 2018. Kansas City, MO.

Greenhalgh, S. P., **Staudt Willet**, K. B., Rosenberg, J. M., Akcaoglu, M., & Koehler, M. J. (2018, April). *Timing is everything: Comparing synchronous and asynchronous modes of Twitter for teacher professional learning.* Paper presented at the American Educational Research Association (AERA) Annual Meeting 2018. New York, NY. 

Greenhow, C. M., Brandon, D. L., Greenhalgh, S. P., Koehler, M. J., **Staudt Willet**, K. B., & Li, J. (2018, April). *Tweeting toward the PhD: Exploring new scholars’ practices with social media.* Paper presented at the American Educational Research Association (AERA) Annual Meeting 2018. New York, NY.

Greenhalgh, S. P., **Staudt Willet**, K. B., Rosenberg, J. M., & Koehler, M. J. (2017, November). *No accounting for theory? The case for an affinity space approach to educational hashtag research.* Paper presented at the Association for Educational Communications and Technology (AECT) International Convention 2017. Jacksonville, FL.

**Staudt Willet**, K. B. (2017, August). *When a little blue bird flaps its wings: How Twitter is changing the world.* Paper presented at Passion Talks Conference 2017. Google Headquarters, Mountain View, CA.

**Staudt Willet**, K. B. (2016, August). *The strength of the weak ties.* Paper presented at Passion Talks Conference 2016. Google Headquarters, Mountain View, CA.

**Staudt Willet**, K. B. (2014, October). *My journey into user-centered game design.* Paper presented at North American Simulation and Game Association (NASAGA) International Conference 2014. Baltimore, MD.

**Staudt Willet**, K. B. (2013, October). *Tension: My favorite game mechanic.* Paper presented at North American Simulation and Game Association (NASAGA) International Conference 2013. Sarasota, FL.

**Willet**, K. B. (2001, February). *The shortest closed path on an arithmetic surface.* Paper presented at Moravian College Student Mathematics Conference 2001. Bethlehem, PA.

## Invited Talks

**Staudt Willet**, K. B. (2017, November). *Once more unto the practicum, dear friends: Research lessons from studying social interactions on social media.* Talk for EPET program brownbag seminar at Michigan State University: East Lansing, MI. 

**Staudt Willet**, K. B. (2016, August). *How did we get here?* Keynote address at Passion Talks Conference 2016. Fremont, CA.

**Staudt Willet**, K. B. (2015, September). *Patterns of online communities.* Webinar presented for Indigitous Sessions. Online.

**Staudt Willet**, K. B. (2014, March). *What games say.* Guest lecture for an undergraduate course in Film & Media at Millersville University: Millersville, PA. 

# Awards & Funding

*Summer Research Renewable Fellowship* - $6,000/year x 2 years \hfill 2018-2019  
Michigan State University, College of Education \hfill East Lansing MI

*Outstanding Paper Award* \hfill 2017  
SITE International Conference \hfill Austin TX

*Best Existing Film* \hfill 2014  
Code for the Kingdom Hackathon \hfill Austin TX

*Presidential Fellowship* - $20,000/year x 3 years \hfill 2000-2003  
Bucknell University \hfill Lewisburg PA

# Service

*Graduate Student Representative*, Research & Theory Division \hfill 2018-2019  
Association for Educational Communications & Technology (AECT)

*Session Presider/Chair* \hfill 2018  
AERA Annual Meeting (New York NY)  
SITE International Conference (Washington DC)

*Assistance with Content Analysis for Doctoral Dissertation* \hfill 2018  
With Colin Terry (Doctoral Candidate)

*Science, Technology, & Innovation Track Chair* \hfill 2017  
*Conference Executive Committee Member* \hfill 2017  
*Conference Program Committee Member* \hfill 2017  
Passion Talks Conference, Mountain View CA

*Graduate Student Ad-Hoc Reviewer* \hfill 2016  
With Dr. Christine Greenhow (Faculty Reviewer), *Learning, Media and Technology*

*Hackathon Mentor Coordinator* \hfill 2015  
*Hackathon Core Leadership Team Member* \hfill 2015  
Urbana International Conference, St. Louis MO

*Board Member* \hfill 2013-2015  
*Conference Committee Member* Seattle WA Conference \hfill 2015  
*Conference Committee Member* Baltimore MD Conference \hfill 2014  
North American Simulation and Game Association

# Professional Experience

*Co-Founder* \hfill 2018-present  
Birch Wayfinders, LLC \hfill Remote  
* Consulted with Nautilus Trackers, LLC on building machine learning into a hybrid training model

*Graduate Assistant/Instructor* \hfill 2017-present  
Department of Counseling, Educational Psychology, & Special Education \hfill East Lansing MI  
Michigan State University, College of Education  
* Taught CEP 416 - Teaching & Learning with Technology (Undergraduate)  
* Taught CEP 817 -  Learning Technology through Design (Master’s)  
* Taught CEP 820 - Teaching Students Online (Master’s)

*Founding National Director* – Ministry in Digital Spaces \hfill 2014-2017  
InterVarsity Christian Fellowship/USA \hfill United States  
* Grew core staff team from 1 to 12  
* Oversaw 51 projects related to online community building  
* Supervised 8 project leads  
* Hosted and directed 5 think tank gatherings  
* Managed annual budget of $500k  
* Raised over $100k annually from individual donors

*Area Director* \hfill 2009-2014  
InterVarsity Christian Fellowship/USA \hfill South Central Pennsylvania  
* Supervised 17 different staff  
* Directed 11 conferences for students from 7 colleges  
* Delivered more than 100 talks at 13 different colleges and 8 conferences  
* Designed, developed, and facilitated 3 board/card games for training staff and students  
* Developed and facilitated 30 training seminars for staff and students  
* Raised over $100k annually from individual donors

*Associate Area Director* \hfill 2009-2014  
InterVarsity Christian Fellowship/USA \hfill South Central Pennsylvania  
* Supervised 1 staff  
* Trained 4 interns  
* Raised over $100k annually from individual donors

*Chapter Planter* – Lebanon Valley College; Millersville University; Penn State Harrisburg \hfill 2007-2009  
InterVarsity Christian Fellowship/USA \hfill South Central Pennsylvania  
* Started chapters at 3 college campuses

*Director* – Summer Urban Program \hfill 2006; 2009-2012  
InterVarsity Christian Fellowship/USA \hfill Lancaster PA  
* Designed and facilitated five 6-week immersive learning programs for undergraduate students  
* Received training in Mexico City, Mexico

*Director* – Summer Global Program \hfill 2005  
InterVarsity Christian Fellowship/USA \hfill Manila, Philippines  
* Designed and facilitated a 6-week immersive, experiential learning program for undergraduate students  
* Received training in Addis Ababa, Ethiopia

*Campus Staff Member* – Franklin & Marshall College \hfill 2003-2007  
InterVarsity Christian Fellowship/USA \hfill Lancaster PA  
* Trained, coached, and supported more than 50 different undergraduate student volunteer leaders  
* Participated in a National Chapter Building Cohort (2006–2007)  
* Apprenticed under international students to learn to cook food from Taiwan, China, Thailand, Japan, India, Nigeria, and Ghana  
* Raised over $50k annually from individual donors

*Research Assistant* – Department of Sociology \hfill 2002-2003  
Bucknell University, College of Arts & Sciences \hfill Lewisburg PA  
* Reviewed literature in social psychology and situational identity

*Research Assistant* – Department of Mathematics \hfill 2000-2002  
Bucknell University, College of Arts & Sciences \hfill Lewisburg PA  
* Assisted with research in L-functions and Maass form deformations

*Summer Research Experience for Undergraduates* (REU) – Department of Mathematics \hfill 2000  
Bucknell University, College of Arts & Sciences \hfill Lewisburg PA  
* Assisted with research in L-functions and Maass form deformations

*Calculus Tutor* – Department of Mathematics \hfill 1999-2000  
Bucknell University, College of Arts & Sciences \hfill Lewisburg PA

# Further Training
*Methods for Analyzing and Modeling Textual Data* \hfill 2018  
Summer School Series on Methods for Computational Social Science \hfill Los Angeles CA

*The Data Scientist’s Toolbox* \hfill 2018  
Certificate – Johns Hopkins University \hfill Coursera.org

*R Programming* \hfill 2017  
Certificate – Johns Hopkins University \hfill Coursera.org

*Serious Game Design and Research* \hfill 2014  
Graduate Certificate – MSU College of Communication Arts & Sciences \hfill East Lansing MI

*Game Design and Facilitation* \hfill 2012  
Workshop Certificate – The Thiagi Group at NASAGA \hfill Columbus OH

# Professional Affiliations

*Association for Educational Communications & Technology* (AECT)  
Research & Theory Division

*American Educational Research Association* (AERA)  
Division C – Learning and Instruction  
Division K – Teaching and Teacher Education  
Teaching as an Agent of Change in Teaching & Learning (TACTL) SIG

*Association of Internet Researchers* (AoIR)

*Society for Information Technology and Teacher Education* (SITE)  
Social Media SIG

# References

Available upon request, though likely would include my PhD advisors, Dr. Matthew J. Koehler and Dr. Christine M. Greenhow.

---

